### ISSUE TITLE
Unused variables.

### ISSUE THREAD

**Issue by finnhodgkin** [tyeung2017/sunsetly#15]
Try to remove unused variables as you go. It's really easy to end up with unnecessary requires if you don't stay vigilant and remove as you go. 

handlers.js requires the https module but doesn't use it.

**Comment by Heathercoraje** [comment]
We've removed unnecessary require(https) on handlers.js
Couldn't find else more. Maybe give us hint?

**Comment by finnhodgkin** [comment]
Lol that may be the only one. I was just sprouting generalities when I saw the first one :see_no_evil:
