### ISSUE TITLE
Results for something that doesn't make sense

### ISSUE THREAD

**Issue by veredrec** [tyeung2017/sunsetly#18]
If you search for something like "nnn" you will still get results but it is not clear for what.
It makes more sense to present the place as well, so you know what the API returns, for the closest results to your search.

**Comment by Heathercoraje** [comment]
It's because of google api we are using. If it is a short random string, google tries very hard to find a place and return you the most relevant location. We've add some line to make the result more sense. Please have a look and close the issue. Thanks.
