### ISSUE TITLE
writing headers in router

### ISSUE THREAD

**Issue by mattlub** [tyeung2017/sunsetly#25]
does it work to write a header like this?

https://github.com/tyeung2017/sunsetly/blob/master/src/router.js#L11

**Comment by Heathercoraje** [comment]
https://github.com/tyeung2017/sunsetly/blob/master/test/test.js#L51

we've add a test for the header.
please have a look and close the issue.
thanks!

**Comment by mattlub** [comment]
your test tests the status codes not the headers. I believe you've implemented it wrong, see the docs:
https://nodejs.org/api/http.html#http_response_writehead_statuscode_statusmessage_headers

And please don't close my issues 😄
