### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by finnhodgkin** [tyeung2017/sunsetly#9]
Not sure how the travis build is passing when my local tests fail. Looks like it's due to different dates/days :man_shrugging: : :clock1:

**Comment by tyeung2017** [comment]
yes, we did the test yesterday and the time that we checked in the test is today.

fixed

**Comment by Heathercoraje** [comment]
please have a look and close the issue. thanks!

**Comment by finnhodgkin** [comment]
There's no commit reference. How do I find the fix? 

If you forget to reference relevant issues just pop a comment on the commit. I'll trust that you fixed it this time :smile:
